import type { CategoryId, MenuItem } from "@/types";

export const categories: {
  id: CategoryId | "all";
  label: string;
  emoji: string;
  image?: string;
}[] = [
  { id: "all", label: "Todo", emoji: "🍽️" },
  { id: "cachapas", label: "Cachapas", emoji: "🌽", image: "/cats/cachapa.jpg" },
  { id: "burgers", label: "Burgers", emoji: "🍔", image: "/cats/burger.jpg" },
  { id: "perros", label: "Perros", emoji: "🌭", image: "/cats/perros.jpg" },
  { id: "parrilla", label: "Parrilla", emoji: "🥩", image: "/cats/parrilla.jpg" },
  { id: "bebidas", label: "Bebidas", emoji: "🥤", image: "/cats/bebidas.jpg" },
];

export const products: MenuItem[] = [
  // --- Cachapas ---
  {
    id: "cachapa-dosis",
    name: "Cachapa Dosis",
    desc: "Cachapa rellena de queso de mano y carne mechada",
    price: 8.5,
    rating: 4.9,
    reviews: "3.2K",
    icon: "cachapa",
    category: "cachapas",
    tag: "best",
    tagLabel: "Estrella",
  },
  {
    id: "cachapa-queso",
    name: "Cachapa de Queso",
    desc: "Cachapa de maíz tierno con queso de mano fundido",
    price: 6,
    rating: 4.7,
    reviews: "2.1K",
    icon: "cachapa",
    category: "cachapas",
  },
  {
    id: "cachapa-catira",
    name: "Cachapa Catira",
    desc: "Cachapa con queso amarillo y mantequilla",
    price: 7.5,
    rating: 4.6,
    reviews: "1.5K",
    icon: "cachapa",
    category: "cachapas",
  },
  {
    id: "cachapa-mixta",
    name: "Cachapa Mixta",
    desc: "Cachapa con queso, carne mechada y jamón",
    price: 10,
    rating: 4.8,
    reviews: "2.4K",
    icon: "cachapa",
    category: "cachapas",
  },
  // --- Burgers ---
  {
    id: "burger-doble-dosis",
    name: "Burger Doble Dosis",
    desc: "Doble carne, queso cheddar, tocineta y papas",
    price: 9.99,
    rating: 4.7,
    reviews: "2.8K",
    icon: "burger",
    category: "burgers",
    tag: "popular",
    tagLabel: "Popular",
  },
  {
    id: "burger-clasica",
    name: "Burger Clásica",
    desc: "Carne 100% res, queso americano y salsa de la casa",
    price: 7.5,
    rating: 4.6,
    reviews: "1.9K",
    icon: "burger",
    category: "burgers",
  },
  {
    id: "burger-bbq",
    name: "Burger BBQ",
    desc: "Carne a la parrilla, cebolla caramelizada y salsa BBQ",
    price: 8.99,
    rating: 4.7,
    reviews: "1.2K",
    icon: "burger",
    category: "burgers",
  },
  {
    id: "burger-pollo",
    name: "Burger de Pollo",
    desc: "Pechuga de pollo crocante, lechuga y mayo de la casa",
    price: 7.99,
    rating: 4.5,
    reviews: "980",
    icon: "burger",
    category: "burgers",
  },
  // --- Perros ---
  {
    id: "perro-especial",
    name: "Perro Especial",
    desc: "Perro con todos los toppings + papas",
    price: 6.5,
    rating: 4.6,
    reviews: "1.9K",
    icon: "hotdog",
    category: "perros",
    tag: "save",
    tagLabel: "Ahorra 15%",
  },
  {
    id: "perro-sencillo",
    name: "Perro Sencillo",
    desc: "Salchicha, repollo, salsa de la casa y papa tostada",
    price: 4.5,
    rating: 4.4,
    reviews: "860",
    icon: "hotdog",
    category: "perros",
  },
  {
    id: "perro-doble",
    name: "Perro Doble",
    desc: "Doble salchicha con queso y tocineta",
    price: 7.5,
    rating: 4.7,
    reviews: "740",
    icon: "hotdog",
    category: "perros",
  },
  // --- Parrilla ---
  {
    id: "parrillada-mixta",
    name: "Parrillada Mixta",
    desc: "Carne, pollo y chorizo a la parrilla + guarniciones",
    price: 16.9,
    rating: 4.9,
    reviews: "980",
    icon: "parrilla",
    category: "parrilla",
    tag: "new",
    tagLabel: "Nuevo",
  },
  {
    id: "churrasco-completo",
    name: "Churrasco Completo",
    desc: "Churrasco con tostones, ensalada y chimichurri",
    price: 14.5,
    rating: 4.8,
    reviews: "720",
    icon: "parrilla",
    category: "parrilla",
  },
  {
    id: "pechuga-plancha",
    name: "Pechuga a la Plancha",
    desc: "Pechuga de pollo con guarniciones a elegir",
    price: 9.9,
    rating: 4.6,
    reviews: "640",
    icon: "parrilla",
    category: "parrilla",
  },
  // --- Bebidas ---
  {
    id: "coca-cola",
    name: "Coca-Cola 500ml",
    desc: "Bebida gaseosa helada",
    price: 1.5,
    rating: 4.5,
    reviews: "5.1K",
    icon: "bebida",
    category: "bebidas",
  },
  {
    id: "agua-mineral",
    name: "Agua Mineral",
    desc: "Botella de agua 500ml",
    price: 1,
    rating: 4.3,
    reviews: "2.8K",
    icon: "bebida",
    category: "bebidas",
  },
  {
    id: "jugo-natural",
    name: "Jugo Natural",
    desc: "Naranja, parchita o piña",
    price: 2.5,
    rating: 4.7,
    reviews: "1.4K",
    icon: "bebida",
    category: "bebidas",
  },
  {
    id: "malta",
    name: "Malta",
    desc: "Malta Polar bien fría",
    price: 2,
    rating: 4.6,
    reviews: "1.7K",
    icon: "bebida",
    category: "bebidas",
  },
];

export function findProduct(id: string): MenuItem | undefined {
  return products.find((p) => p.id === id);
}
